### ISSUE TITLE
希望增加 ACL 文件设置的功能

### ISSUE THREAD

**Issue by mpco** [shadowsocksr/ShadowsocksX-NG#103]
ShadowsocksX-NG所使用的Shadowsocks-libev已经支持ACL分流，希望能够设置 ACL 文件。
有些软件好像并不支持Mac系统的PAC网络代理。

**Comment by qinyuhang** [comment]
ACL 文件的使用wiki等 不知道你可有？或者何处可查阅？@mpco

**Comment by mpco** [comment]
@qinyuhang 不好意思，我只看到 ss(r)-libev 中可以使用ACL：
```
 [--acl <acl_file>]         config file of ACL (Access Control List)
                                  only available in local and server mode
```
具体的语法和wiki都没有找到

**Comment by qinyuhang** [comment]
没关系，分支已经创建了，将会在此分支上发展一下

**Comment by mpco** [comment]
@qinyuhang  [ACL 文件简析 – 赵](https://www.zhaoj.in/read-3938.html)

**Comment by qinyuhang** [comment]
目前确实还没有人维护一个好的ACL文件，我自己试着做了一个acl文件，还是会导致公司内部excahgen邮箱出问题，所以现在还在斟酌

**Comment by mpco** [comment]
@qinyuhang  在我的想法中，增加ACL配置功能，只是在配置窗口上加了个输入 ACL 路径的输入栏，在运行ss-local时后面加上 -acl xxx.acl，工作量应该不大吧。Global Mode 下使用设置的ACL配置进行分流控制。需要的人自己配置着用，不需要的照旧使用Global Mode就好。

**Comment by qinyuhang** [comment]
这个会参考win和android版本的

**Comment by mpco** [comment]
@qinyuhang  感谢！

**Comment by qinyuhang** [comment]
现在已经添加。可下载最新的release使用。

**Comment by arfaWong** [comment]
[https://github.com/ACL4SSR/ACL4SSR](url)
这个ACL文件不错
