### ISSUE TITLE
gpg  verify 

### ISSUE THREAD

**Issue by AZmake** [shadowsocksr/ShadowsocksX-NG#105]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

$:~ $ gpg --verify /Downloads/ShadowsocksX-NG-R8.dmg.sig /Downloads/ShadowsocksX-NG-R8.dmg
gpg: Signature made 一  2/27 15:18:57 2017 CST using RSA key ID 73EB5E11
gpg: requesting key 73EB5E11 from hkps server hkps.pool.sks-keyservers.net
gpgkeys: HTTP fetch error 35: gnutls_handshake() failed: The TLS connection was non-properly terminated.
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: General error
gpg: Can't check signature: No public key

**Comment by qinyuhang** [comment]
Please import my Pub key first, and set it as ultimate trust.

**Comment by AZmake** [comment]
thanks a lot
