### ISSUE TITLE
10.12.3 从其它模式切回白名单就5国 重启???

### ISSUE THREAD

**Issue by blankhang** [shadowsocksr/ShadowsocksX-NG#109]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.3
- Shadowsocksx-NG-R8 1.3.8-build8

**Comment by blankhang** [comment]
另外新版的服务器测速也没用了..不能显示延迟了

**Comment by qinyuhang** [comment]
Please upload more information about system or the app itself, honestly me never experience a 5 country problem causing by SS-NG-R

**Comment by lydasia** [comment]
同10.12.3，两台Mac(一黑一白)均无此现象，应该是你自己的问题。这个小应用也几乎不可能引发五国报错。

**Comment by blankhang** [comment]
可能是我最新版的 RNMP 的问题..
并不是 SSR 造成..抱歉
