### ISSUE TITLE
自定义PAC规则如何覆盖原有规则

### ISSUE THREAD

**Issue by thesadboy** [shadowsocksr/ShadowsocksX-NG#118]
用户定义的PAC规则无法覆盖本身的规则
例如规则中有
@@||fonts.googleapis.com
然后我添加
||fonts.googleapis.com
但是域名 fonts.googleapis.com 依然无法走代理，这种情况如何解决？

**Comment by thesadboy** [comment]
难道不应该是用户自定义规则的优先级高么？

**Comment by qinyuhang** [comment]
fixed in 720afb1b695129cf0393a21496484876efd44612

**Comment by thesadboy** [comment]
great...thx

**Comment by i1052** [comment]
R11和12似乎还是有问题，我在自定义规则里添加了以下两句：

||fonts.gstatic.com
||gstatic.com

前几天刚更新了R11还生效的样子，这两天发现依然无法走代理；
我把proxy.pac文件下载回来打开，查找gstatic可以得到下面结果：
  "||fonts.gstatic.com",
  "||gstatic.com",
  "||gstatic.com",
  "@@||csi.gstatic.com",
  "@@||fonts.gstatic.com",

似乎还是有一条规则将fonts.gstatic.com给禁掉了。

**Comment by qinyuhang** [comment]
try `||*gstatic.com`

**Comment by i1052** [comment]
it works. thx.

**Comment by thesadboy** [comment]
我的仍然无效。。。。
用 ||*googleapis.com
或者 ||fonts.googleapis.com
但是在pac中仍然会看到 @@||fonts.googleapis.com
给禁用掉了。。。

**Comment by qinyuhang** [comment]
Try `||*.googleapis.com <http://googleapis.com/>` ?

**Comment by thesadboy** [comment]
依然无效。。。
设置后仍然无法访问类似 
https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600
这样的资源。。。

**Comment by i1052** [comment]
我又回来了，目前经过观察发现，这东西工作不稳定，有时候能访问fonts.gstatic.com，有时候不能，表现为Safari打开YouTube页面所有文字都不显示，但图片和视频是正常的。

而且经过开关代理/切换全局再切回来之类的方法整几下又好了，过一段时间之后又出现了。

我目前的环境不能完全排除DNS的问题，不过pac文件里会一直存在"@@||fonts.gstatic.com"，所以估计也和这个有关系。
当然最理想的情况是，
当自定义规则里存在"||fonts.gstatic.com"时，生成的pac文件里一定不包含"@@||fonts.gstatic.com"

**Comment by qinyuhang** [comment]
R U sure it is the problem with the app? @i1052 @Nick Zhang

Did U check the ss-local.log see if the is log lick `connect reset by peer` ? 

Personally, I never experienced UTube page text not appears and I can visit https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600 <https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600>  and    http://fonts.gstatic.com/s/opensans/v10/DXI1ORHCpsQm3Vp6mXoaTS3USBnSvpkopQaUR-2r7iU.ttf <http://fonts.gstatic.com/s/opensans/v10/DXI1ORHCpsQm3Vp6mXoaTS3USBnSvpkopQaUR-2r7iU.ttf>

**Comment by i1052** [comment]
There're some 'connect reset by peer' in the log, but none at the time when the issue occurring.

I'll try to serve a static proxy.pac without "@@||fonts.gstatic.com" on my local webserver instead of that one which generated by ShadowsocksX-NG. Then I'll keep watching if there's a same issue.

**Comment by qinyuhang** [comment]
Fixed
