### ISSUE TITLE
关于 二维码生成问题

### ISSUE THREAD

**Issue by ChengLuffy** [shadowsocksr/ShadowsocksX-NG#119]
**System and Shadowsocksx-NG-R8 version:**
1.3.9(9) 
此发行版本生成的二维码不符合 [breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme](https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme) 中的说明。

**Comment by qinyuhang** [comment]
OK I'll check it later

发自我的 iPhone

**Comment by qinyuhang** [comment]
https://github.com/shadowsocksr/ShadowsocksX-NG/issues/127

**Comment by qinyuhang** [comment]
@ChengLuffy `udpport参数及uot目前仅C#客户端支持`你是说这里？

**Comment by ChengLuffy** [comment]
应该是关于 **URL safe base64**

**Comment by qinyuhang** [comment]
safe base64的问题之前已经解决过，目前我在实践中没有遇到不能解析的。不知道你有遇到的是什么样的？

**Comment by ChengLuffy** [comment]
当时用的是 `Potatso 2`, 其作者 @icodesign 声称严格按照  [SSR-QRcode-scheme](https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme) 进行解析，然而无法解析 生成的 二维码

**Comment by ChengLuffy** [comment]
晚上有时间我详细解析下补充说明

**Comment by qinyuhang** [comment]
OK

**Comment by icodesign** [comment]
没错，请参照 https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme 的格式说明生成URL

**Comment by ChengLuffy** [comment]
我感觉你们直接沟通效果比我测试去好，今晚加班，两位加油

**Comment by qinyuhang** [comment]
Fixed
