### ISSUE TITLE
Where can I download the app?

### ISSUE THREAD

**Issue by pqpo** [shadowsocksr/ShadowsocksX-NG#122]
Where can I download the app?

**Comment by qinyuhang** [comment]
github.com/shadowsocksr/shadowsocksX-NG/releases <http://github.com/shadowsocksr/shadowsocksX-NG/releases>

**Comment by qinyuhang** [comment]
github.com/shadowsocksr/shadowsocksX-NG/releases <http://github.com/shadowsocksr/shadowsocksX-NG/releases>
