### ISSUE TITLE
R8-Beta10 图标状态异常 

### ISSUE THREAD

**Issue by gaocuo** [shadowsocksr/ShadowsocksX-NG#123]
版本：R8，Beta10
状况：关闭shadowsocks后，也就是shadowsocks 处于off的状态，关掉程序后打开，图标变成开启的状态，但这时候 shadowsocks 还是处于off的状态。

![qq20170405-143107](https://cloud.githubusercontent.com/assets/2223221/24692717/ea214aa4-1a0c-11e7-809f-32b29dca4bcd.png)

**Comment by qinyuhang** [comment]
Fixed
