### ISSUE TITLE
SSR链接

### ISSUE THREAD

**Issue by nicbh** [shadowsocksr/ShadowsocksX-NG#127]
请问客户端能不能输入SSR链接来添加服务器啊？扫二维码好像不太好用，点了之后没有反应。

**Comment by qinyuhang** [comment]
推荐导入json config 文件

**Comment by qinyuhang** [comment]
测试了几个 ssr 链接并为之发现有这个问题，不知可否自行base64解密一下然后校验格式，或者不愿意的话，可以用我的gpg公钥加密以后发给我，我来校验。

**Comment by nicbh** [comment]
测试的是免费账号就不加密了。
来自于https://doub.bid/sszhfx/
ssr://MTcyLjEwNC41NS4yMzA6MjMzMzphdXRoX2FlczEyOF9zaGExOmNoYWNoYTIwOnRsczEuMl90aWNrZXRfYXV0aDpaRzkxWWk1cGJ3PT0=
解码后是ssr://172.104.55.230:2333:auth_aes128_sha1:chacha20:tls1.2_ticket_auth:ZG91Yi5pbw==
看了下wiki里面的规范没搞懂/?后面的是不是可以省略。

**Comment by breakwa11** [comment]
@nicbh 这个格式错误，等于号不应该保留

**Comment by nicbh** [comment]
哪有多余的等于号？

**Comment by qinyuhang** [comment]
正确的格式应该是 `ssr://MTcyLjEwNC41NS4yMzA6MjMzMzphdXRoX2FlczEyOF9zaGExOmNoYWNoYTIwOnRsczEuMl90aWNrZXRfYXV0aDpaRzkxWWk1cGJ3PT0` 后面的等号不应该有。SSNG-R生成的目前也有，需要彻底去掉。

**Comment by qinyuhang** [comment]
@nicbh 不要把`/?`后面省略掉是什么？

**Comment by nicbh** [comment]
可是无论是一些在线转换还是python的base64包都会带有等号啊，所以都要去掉咯？
/?是指ssr://base64(host:port:protocol:method:obfs:base64pass/?obfsparam=base64param&protoparam=base64param&remarks=base64remarks&group=base64group&udpport=0&uot=0)格式中的/?，我现在知道是能省略掉的了。
