### ISSUE TITLE
~/Library/Application Support/ShadowsocksX-NG/ 中不存在privoxy 及ss-local

### ISSUE THREAD

**Issue by Joney0210** [shadowsocksr/ShadowsocksX-NG#128]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.11.6
- Shadowsocksx-NG-R8 1.3.9-build10

在安裝了build10 及9 ，執行後無法連接Server端。
檢查了~/Library/Application Support/ShadowsocksX-NG/後發現，在其中的privoxy 及ss-local連結目的的檔案不見了。

提取App檔案中的privoxy 及ss-local放入相應目錄後，功能正常。
<img width="625" alt="2017-04-10 19 15 30" src="https://cloud.githubusercontent.com/assets/13252705/24859199/27713518-1e22-11e7-917e-53e0a784aa81.png">

**Comment by qinyuhang** [comment]
Thanks, will keep tracking it.
