### ISSUE TITLE
彻底卸载 ShadowsocksX-NG 的方法

### ISSUE THREAD

**Issue by SharpChen** [shadowsocksr/ShadowsocksX-NG#129]
##  1、ss-local 进程无法关闭
当卸载了 ShadowsocksX-NG 时，ss-local 进程依然在后台运行，也能正常翻墙，而且 kill 这个进程也没用，太可怕了，不知道是不是 bug ，感觉后台一直跑着 ss-local 这个进程好可怕。
```
ss-local  97336 sharp    6u  IPv4 0x45cdfef5913e2d9      0t0  TCP localhost:cplscrambler-lg (LISTEN)

ss-local  97336 sharp    7u  IPv4 0x45cdfef6bae29e1      0t0  TCP localhost:cplscrambler-lg->localhost:59845 (ESTABLISHED)

ss-local  97336 sharp    8u  IPv4 0x45cdfef5e061ef9      0t0  TCP localhost:cplscrambler-lg->localhost:59853 (ESTABLISHED)

ss-local  97336 sharp    9u  IPv4 0x45cdfef6be0c2d9      0t0  TCP localhost:cplscrambler-lg->localhost:55174 (ESTABLISHED)

ss-local  97336 sharp   11u  IPv4 0x45cdfef5d202601      0t0  TCP 10.10.20.56:55176->391658414.zhujike.vps:29363 (ESTABLISHED)

ss-local  97336 sharp   13u  IPv4 0x45cdfef5bf61bd1      0t0  TCP 10.10.20.56:59847->391658414.zhujike.vps:29363 (ESTABLISHED)

ss-local  97336 sharp   14u  IPv4 0x45cdfef5c9a77f1      0t0  TCP 10.10.20.56:59856->391658414.zhujike.vps:29363 (ESTABLISHED)
```

## 2、PAC 手动配置
是否能添加手动配置 PAC 的功能，现在只能更新网上的，这样感觉不太方便，原来的 ShadowsocksX-2.6.5 都能自己配置 PAC，不知道为什么现在取消了。

**Comment by qinyuhang** [comment]
ss-local is started by daemon plist, just run `launchctl unload "$HOME/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist"` then kill ss-local.
### **OR YOU SHOULD STOP DISCONNECTION BEFORE REMOVE THE APP.**
### There is manual edit PAC.

**Comment by SharpChen** [comment]
xx

**Comment by SharpChen** [comment]
**你说的 manual edit PAC 是这个吗？**
![mode](http://ohoxzxrb2.bkt.clouddn.com/mode.png)
![rules](http://ohoxzxrb2.bkt.clouddn.com/userRules.png)
**在 ShadowsocksX-2.6.5 是这样编辑 PAC 的：**
![rules](http://ohoxzxrb2.bkt.clouddn.com/gfwlist.png)

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/issues/317 <https://github.com/shadowsocks/ShadowsocksX-NG/issues/317>
