### ISSUE TITLE
R8 11 会切代理模式导致五国?

### ISSUE THREAD

**Issue by blankhang** [shadowsocksr/ShadowsocksX-NG#133]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4
- Shadowsocksx-NG-R8 1.3.9-R8 11

从 R8 9 更新到 R8 11 版本后 
尝试从 PAC 改到 全局 又五国了....
Anonymous UUID:       F734653E-3483-87E0-5945-XXXXX

ss  log:

Apr 21 09:11:35 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 09:11:35 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.
Apr 21 09:11:37 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 09:11:37 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.
Apr 21 10:54:28 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.
Apr 21 10:54:28 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[496]): Service exited with abnormal code: 15
Apr 21 10:54:28 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 11:05:17 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[1209]): Service exited with abnormal code: 15
Apr 21 11:05:22 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.
Apr 21 11:05:22 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 16:24:26 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[1306]): Service exited with abnormal code: 15
Apr 21 16:26:07 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 16:26:07 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.
Apr 21 16:27:33 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[521]): Service exited with abnormal code: 15
Apr 21 16:27:33 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): This service is defined to be constantly running and is inherently inefficient.
Apr 21 16:27:33 blankdeMacbook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): This service is defined to be constantly running and is inherently inefficient.

sys log

Fri Apr 21 16:26:02 2017

*** Panic Report ***
panic(cpu 2 caller 0xffffff801dc011bd): Kernel trap at 0xffffff7fa17d3404, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0x000000010c97c000, CR3: 0x00000003dac210b6, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x0000000000000000, RDX: 0x0000000000000000
RSP: 0xffffff920bceb800, RBP: 0xffffff920bceb850, RSI: 0xffffff80408f1950, RDI: 0x000000000000001e
R8:  0xffffff920bceb6b4, R9:  0xffffff920bcebdd8, R10: 0x0000000000000000, R11: 0xffffff8042209930
R12: 0xc0ffee3cc981a188, R13: 0xffffff920bceb99c, R14: 0xffffff920bceb860, R15: 0xffffff80408f1800
RFL: 0x0000000000010286, RIP: 0xffffff7fa17d3404, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000010c97c000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff81fcdc5df0 : 0xffffff801daec3ec 
0xffffff81fcdc5e70 : 0xffffff801dc011bd 
0xffffff81fcdc6050 : 0xffffff801da9d543 
0xffffff81fcdc6070 : 0xffffff7fa17d3404 
0xffffff920bceb850 : 0xffffff7fa17d3e33 
0xffffff920bcebcd0 : 0xffffff801dff3224 
0xffffff920bcebe20 : 0xffffff801dfc9d7d 
0xffffff920bcebe80 : 0xffffff801dfd9e7a 
0xffffff920bcebf50 : 0xffffff801e025695 
0xffffff920bcebfb0 : 0xffffff801da9dd46 
      Kernel Extensions in backtrace:
         com.adguard.nfext(5.0)[E7184035-9F57-3A21-8690-7A8D988117C6]@0xffffff7fa17d2000->0xffffff7fa17fcfff

BSD process name corresponding to current thread: Google Chrome

Mac OS version:
16E195

**Comment by qinyuhang** [comment]
checked at your kernel info：

```
Kernel Extensions in backtrace:
com.adguard.nfext(5.0)[E7184035-9F57-3A21-8690-7A8D988117C6]@0xffffff7fa17d2000->0xffffff7fa17fcfff

BSD process name corresponding to current thread: Google Chrome
```

Maybe U can check compatibility of adguard. Did you tried **uninstall** adguard?
> 在 2017年4月21日，16:35，blankhang <notifications@github.com> 写道：
> 
> panic(cpu 2 caller 0xffffff801dc011bd): Kernel trap at 0xffffff7fa17d3404, type 13=general protection, registers:

**Comment by qinyuhang** [comment]
Seem adguard problem, not SSR problem
