### ISSUE TITLE
图标下面有个G是什么意思?

### ISSUE THREAD

**Issue by xwj1003** [shadowsocksr/ShadowsocksX-NG#136]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4
- Shadowsocksx-NG 1.3.9-R8(11)

有的时候好像是M,  
这些字母含义有解释吗?

**Comment by qinyuhang** [comment]
P = PAC auto mode
M = Manual mode
G = Global mode
W = White list mode

**Comment by qinyuhang** [comment]
P = PAC auto mode
M = Manual mode
G = Global mode
W = White list mode

**Comment by xwj1003** [comment]
thanks

**Comment by supermanxiacheng** [comment]
为什么我的10.12.4, 4个状态都没有字母,光秃秃的
