### ISSUE TITLE
升级到最新版本后用不了

### ISSUE THREAD

**Issue by exxfzc** [shadowsocksr/ShadowsocksX-NG#142]
mac 10.12.1系统,帐号是正常的,在win下可以用;
之前用旧版本没有问题,现在升级到最新版本后,就发现用不了了;

是要上传系统日志的吗....不太会...

**Comment by qinyuhang** [comment]
如果是 auth_sha1_v4 问题 已经在最新release修复 https://github.com/shadowsocksr/ShadowsocksX-NG/releases/tag/1.4.0-R8-build2
