### ISSUE TITLE
图标不清晰

### ISSUE THREAD

**Issue by supermanxiacheng** [shadowsocksr/ShadowsocksX-NG#143]
- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build10

现在模式图标的字母和小飞机图标部分重合在一起的,好难看.

给个建议,其实小飞机旁边另起3个字符位, 分为 全局,手动,PAC,白名单.  比图标好多了

或者把图标弄得更美观点,也行....

**Comment by octww** [comment]
字母放飞机左边就不会重叠了

**Comment by qinyuhang** [comment]
fixed
