### ISSUE TITLE
同时登录两个用户之后，有几率失效

### ISSUE THREAD

**Issue by Sharnodra** [shadowsocksr/ShadowsocksX-NG#145]
我的Mac设置了两个用户，在主用户A上开了这个SS程序，可用。
之后我切换至用户B，用户B不用开启SS程序也能访问外面的世界。
再切换回用户A，不知道操作了什么，就失效了，切换至用户B也失效。（失效过3次。。
失效之后，在菜单里无论是选什么模式，用户A和B都会处于失效状态。
最后，我注销了用户B，用户A就正常了，可以访问外面的世界。
我就知道这么多了，本来想试着复现一下怎么才能失效，但没成功。ㄟ(▔,▔)ㄏ

**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG-R8 1.4.0

**Comment by qinyuhang** [comment]
这种需求比较少见。
