### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by LisonFan** [shadowsocksr/ShadowsocksX-NG#148]
白名单模式改成 ACL 之后只加载了 chn.acl，但是 chn.acl 里不包含局域网 ip ，所以导致使用白名单模式会让局域网 ip 走代理

**Comment by LisonFan** [comment]
我弄了一份 chn.acl : https://github.com/LisonFan/SSR-ACL
局域网 ip 的 acl 可以用 : https://github.com/shadowsocksr/shadowsocksr-libev/blob/master/acl/local.acl

**Comment by LisonFan** [comment]
刚刚看了一下源码，更新全部白名单没更新 chn.acl 。。。
本来想动手改一下的，技术太差了，无从下手。。。

**Comment by LisonFan** [comment]
我弄的那份 chn.acl 是 ipip 的 china ip
大概每个月初更新一次，你可以用我那份

**Comment by qinyuhang** [comment]
现在还没有开发到设置远端源更新acl文件。之后会增加的。

**Comment by LisonFan** [comment]
@qinyuhang 先把 local.acl 加上吧

**Comment by qinyuhang** [comment]
https://github.com/shadowsocksr/ShadowsocksX-NG/commit/3ce21085c6ae610e123532117b061d3942ec9e27

Not new release, U may replace this file https://raw.githubusercontent.com/shadowsocksr/ShadowsocksX-NG/3ce21085c6ae610e123532117b061d3942ec9e27/ShadowsocksX-NG/chn.acl in ${HOME}/.ShadowsocksX-NG

**Comment by qinyuhang** [comment]
https://github.com/shadowsocksr/ShadowsocksX-NG/releases/tag/1.4.0-R8-build4 新release可自定义ACL远端下载地址
