### ISSUE TITLE
英语单词写错了

### ISSUE THREAD

**Issue by BenjaminGao** [shadowsocksr/ShadowsocksX-NG#152]
macOS 
1.4.1-R8 build 1
“Update All Wihte List” 这里写错了吧 “Wihte”

![screen shot 2017-05-16 at 12 08 39 pm](https://cloud.githubusercontent.com/assets/16028320/26089452/7d65fee8-3a30-11e7-9419-f57770701bf3.png)

**Comment by qinyuhang** [comment]
Good I'll correct it

**Comment by qinyuhang** [comment]
fixed
