### ISSUE TITLE
MAC OS 10.12.4下各种模式都不能科学上网。

### ISSUE THREAD

**Issue by golmic** [shadowsocksr/ShadowsocksX-NG#155]
同一帐号在安卓下可以正常使用，但是macOS Sierra 10.12.4 没法翻墙，版本 1.4.1-R8 (1)，换网上的公开SS 帐号后可以正常使用，请问可能是哪些问题导致的呢？

**Comment by qinyuhang** [comment]
检查一下有没填写错误，另 按照issue template贴上log。

**Comment by golmic** [comment]
问题解决，原因是服务器域名的问题，改成服务器IP后问题解决。谢谢
