### ISSUE TITLE
点击测速就崩溃,不知道哪里有问题

### ISSUE THREAD

**Issue by wcmbeta** [shadowsocksr/ShadowsocksX-NG#159]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.11.6 
- Shadowsocksx-NG-R8 1.4.1-build1

[ShadowsocksX-NG_2017-05-25-185512.crash.zip](https://github.com/shadowsocksr/ShadowsocksX-NG/files/1028779/ShadowsocksX-NG_2017-05-25-185512.crash.zip)

**Comment by Portan** [comment]
我的也是这样

**Comment by seuplus** [comment]
同样的问题，试了几个版本都是这样

**Comment by wcmbeta** [comment]
下了新版本不会闪退了
