### ISSUE TITLE
进入系统后 ss 无法自动启动

### ISSUE THREAD

**Issue by Spacebody** [shadowsocksr/ShadowsocksX-NG#162]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.5 (16F73)
- Shadowsocksx-NG-R8 1.4.1-R8 (1)

**Expected behavior:已经设置软件开机启动和每次启动自动连接，每次进入系统后 ssr 自动开启**

**Actual behavior:并未自动开启而是处于关闭状态**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

每次

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

[ss-local.log.zip](https://github.com/shadowsocksr/ShadowsocksX-NG/files/1049285/ss-local.log.zip)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

Search for Nothing

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by seuplus** [comment]
OSX 10.11.6 也有同样的问题，开了自启动连接无效

**Comment by Spacebody** [comment]
@seuplus 最新版已经修复了。
