### ISSUE TITLE
建议：增加对 ssr:// URL Scheme 导入多个节点信息的支持

### ISSUE THREAD

**Issue by ZeroClover** [shadowsocksr/ShadowsocksX-NG#165]
ShadowsocksX-NG-R 支持使用 `ssr://` URL Scheme 导入节点信息，但只能导入一个节点的信息

SSR C-sharp 和 SSR Android 以及 iOS 上的 App 都支持使用 `ssr://` 链接导入多个节点，具体方法是将多个节点的 `ssr://` 链接连接起来并用管道符 `|` 来分隔，如 `ssr://xxxxxx|ssr://yyyyyyy|ssr://zzzzzz`

希望 SSX-NG 也能支持此功能。

**Comment by qinyuhang** [comment]
Done in [develop d3bdc73] Now handler multiper config in one ss url #165

**Comment by qinyuhang** [comment]
This feature is available in released binary package.
