### ISSUE TITLE
mac 10.12.1 无法上网

### ISSUE THREAD

**Issue by sunyanyan** [shadowsocksr/ShadowsocksX-NG#166]
**System and Shadowsocksx-NG-R8 version:**

- mac 10.12.1(16B2657)
- Shadowsocksx-NG-R8 1.4.1-R8 (2)

**Steps to reproduce:**

全局模式 上不了网

**How often does this happen?**

每次

**ss-local.log**

ERROR: getpeername: Invalid argument 启动ss时这句话大量出现。

打开网页后提示： 
ERROR: getsockopt error code 0 61
ERROR: getsockopt: Operation now in progress

**Comment by qinyuhang** [comment]
61是connection refused

**Comment by sunyanyan** [comment]
服务器问题吗？ 和 [issue 73](https://github.com/shadowsocksr/ShadowsocksX-NG/issues/73) 一个问题吗？

**Comment by qinyuhang** [comment]
你试试换个节点吧。

**Comment by sunyanyan** [comment]
多谢 换了个服务器 换了个端口 就好了……
