### ISSUE TITLE
Is kcptun a must for shadowsocksx-ng?

### ISSUE THREAD

**Issue by ltzdby** [shadowsocksr/ShadowsocksX-NG#167]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12
- Shadowsocksx-NG-R8 1.4.1-R8-build3

Is kcptun on server side and a configure for kcptun on client side a must for shadowsocksx-ng to run? "ss-local.log" and "privoxy.log" show no abnormal things. However there appears a log file for kcptun and shows that it is looking for a configure file for kcptun and continuously output "no such file or directory".

**Comment by qinyuhang** [comment]
We don't support kcptun (you can find nothing about it in the source code), if you find kcptun problem, I guess it is not related to Shadowsocksx-NG-R8
