### ISSUE TITLE
二维码扫描问题

### ISSUE THREAD

**Issue by hly928** [shadowsocksr/ShadowsocksX-NG#169]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.5
- Shadowsocksx-NG-R8 1.4.1(3)

扫描二维码时服务器密码会少一位

**Comment by hly928** [comment]
BTW:能不能加入通过URL导入的方式？配合universal clipboard就十分方便了

**Comment by qinyuhang** [comment]
支持URL导入。不支持URL批量导入。

**Comment by qinyuhang** [comment]
Now Support URL import multiple config.

**Comment by qinyuhang** [comment]
Cannot reproduce scan QR problem.
