### ISSUE TITLE
求助 無法登陸LINE 

### ISSUE THREAD

**Issue by uitra110** [shadowsocksr/ShadowsocksX-NG#171]
**System and Shadowsocksx-NG-R8 version:**

 macOS 10.12.5 
版本 1.4.1-R8 (3)

求教，無法使用line 

使用PAC模式 
將代理地址
127.0.0.1 ／1086 加入到SOCKS4和SOCKS5以及http中 

SOCKS4 使用line設置的可以使用，但是進入LINE程序仍然無法登入 求解。
全局模式中依舊無法使用 求解答

**Comment by wangxufire** [comment]
![image](https://user-images.githubusercontent.com/6488465/27009366-5cbe1a5c-4ebe-11e7-9e0f-43e220562ad7.png)

**Comment by uitra110** [comment]
![qq20170611-155615](https://user-images.githubusercontent.com/29350636/27009375-9367e0f6-4ebe-11e7-9c76-a055750917a4.png)

**Comment by uitra110** [comment]
@wangxufire  依然無法登陸

**Comment by wangxufire** [comment]
![image](https://user-images.githubusercontent.com/6488465/27009384-1ceb7cac-4ebf-11e7-86da-322a3fded16b.png)

**Comment by uitra110** [comment]
![qq20170611-161641](https://user-images.githubusercontent.com/29350636/27009444-65ccf7d2-4ec1-11e7-96f5-bfe1e26ec4d8.png)
仍然是無法使用
@wangxufire

**Comment by uitra110** [comment]
@wangxufire   可以登陸了 謝謝  想問一下 為什麼代理檢測那會提示錯誤呢

**Comment by uitra110** [comment]
![1](https://user-images.githubusercontent.com/29350636/27009493-d6297cd4-4ec2-11e7-97e6-3bd2ff24490c.png)
![2](https://user-images.githubusercontent.com/29350636/27009494-d6408726-4ec2-11e7-987e-d6c8e35953e0.png)

**Comment by wangxufire** [comment]
我没点过检测，都是直接应用。你可以直接把ss真实地址填过来试试，不用本地的127。

**Comment by uitra110** [comment]
@wangxufire  謝謝 我這個可以使用了  嗯 能+個好友麽 方便交流問題  話說我是怎麼關閉了這個問題啊  求助如何打開
