### ISSUE TITLE
mac下无法访问

### ISSUE THREAD

**Issue by yl23250** [shadowsocksr/ShadowsocksX-NG#180]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 

**Expected behavior:**

按照https://997link.com/?p=222这个来配置的
macbook就是无法打开google.com
让同事用了下windows和手机都巨快

**Comment by qinyuhang** [comment]
是通过二维码倒入的？从面板中找到 gui-config.json 的下载方式 通过导入json文件添加节点试试？

**Comment by 0u0u0** [comment]
@qinyuhang ShadowsocksX-NG 普通版（没有R）就一直有新版 macOS 无法连接的问题
https://github.com/shadowsocks/ShadowsocksX-NG/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by qinyuhang** [comment]
你应该去那个repo提问。

**Comment by 0u0u0** [comment]
@qinyuhang 这叫提问？
