### ISSUE TITLE
是否考虑添加 C# 版的订阅功能？

### ISSUE THREAD

**Issue by arfaWong** [shadowsocksr/ShadowsocksX-NG#186]
是否考虑添加 C# 版的订阅功能？
所用的线路经常变动，有个订阅功能挺不错的。

**Comment by qinyuhang** [comment]
Under development
https://github.com/shadowsocksr/ShadowsocksX-NG/tree/feature/subscribe <https://github.com/shadowsocksr/ShadowsocksX-NG/tree/feature/subscribe>
