### ISSUE TITLE
Doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by Vincent-St** [shadowsocksr/ShadowsocksX-NG#187]
**System and Shadowsocksx-NG 1.5.1 (1) version:**

- macOS 10.13 Beta (17A291m)
- Shadowsocksx-NG-Version 1.5.1 (1)

**Expected behavior:**

macOS High Sierra support

**Actual behavior:**

N/A

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

~/Library/Logs:2017-07-04 08:33:44 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 08:33:49 INFO: listening at 127.0.0.1:1086
 2017-07-04 11:32:01 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 11:32:03 INFO: listening at 127.0.0.1:1086
 2017-07-04 11:35:08 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 11:35:13 INFO: listening at 127.0.0.1:1086
 2017-07-04 16:34:32 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 16:34:34 INFO: listening at 127.0.0.1:1086
 2017-07-04 17:08:16 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 17:08:19 INFO: listening at 127.0.0.1:1086
 2017-07-04 17:11:05 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 17:11:07 INFO: listening at 127.0.0.1:1086
 2017-07-04 20:34:32 INFO: protocol origin
 2017-07-04 20:34:32 INFO: method aes-256-cfb
 2017-07-04 20:34:32 INFO: obfs plain
 2017-07-04 20:34:32 INFO: obfs_param 
 2017-07-04 20:34:32 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 20:34:33 INFO: tcp port reuse enabled
 2017-07-04 20:34:33 INFO: listening at 127.0.0.1:1086
 2017-07-04 20:41:24 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 20:41:29 INFO: listening at 127.0.0.1:1086
 2017-07-04 20:44:33 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 20:44:38 INFO: listening at 127.0.0.1:1086
 2017-07-04 20:48:15 INFO: initializing ciphers... aes-256-cfb
 2017-07-04 20:48:20 INFO: listening at 127.0.0.1:1086

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

default	20:48:10.993798 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
default	20:48:11.057989 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
default	20:48:11.123347 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
default	20:48:11.123655 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	20:48:11.234913 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10645] (3,0)
default	20:48:11.252988 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10645] (3,0)
default	20:48:11.273654 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10645] (3,0)
default	20:48:11.291066 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10645] (3,0)
default	20:48:11.293934 +0800	ShadowsocksX-NG	pac proxy set to off
default	20:48:11.307890 +0800	loginwindow	TAL | kLWDBLogLevel_Internal | -[PersistentAppsSupport applicationQuit:] | for app:ShadowsocksX-NG, _appTrackingState = 2
default	20:48:13.813008 +0800	Spotlight	results: (
    "<SPCoreSpotlightResult> Releases \U00b7 shadowsocksr/ShadowsocksX-NG (com.apple.safari.history): <CSSearchableItem:0x61800043f2c0; uid=C0744A8E8C531E1E2E563142AE14B43D56938FE5AC05289FF3559C8960152F73, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> shadowsocksr/ShadowsocksX-NG: Next Generation of ShadowsocksX https://github.com/shadowsocks/shadowsocks-iOS (com.apple.safari.history): <CSSearchableItem:0x61800042c720; uid=A28FAE879AD99B1C238309308A9071EC85D300D697100266D429A72F90B457FA, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> Sign in to GitHub \U00b7 GitHub (com.apple.safari.history): <CSSearchableItem:0x6180006244c0; uid=6A54318E17A5C01F5AF389661BB84FE7AC815E2B4EAC7133B13A898997C61CFC, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> New Issue \U00b7 shadowsocksr/ShadowsocksX-NG (com.apple.safari.history): <CSSearchableItem:0x618000622e80; uid=71
default	20:48:13.970570 +0800	Spotlight	results: (
    "<SPCoreSpotlightResult> Releases \U00b7 shadowsocksr/ShadowsocksX-NG (com.apple.safari.history): <CSSearchableItem:0x60800043a1a0; uid=C0744A8E8C531E1E2E563142AE14B43D56938FE5AC05289FF3559C8960152F73, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> shadowsocksr/ShadowsocksX-NG: Next Generation of ShadowsocksX https://github.com/shadowsocks/shadowsocks-iOS (com.apple.safari.history): <CSSearchableItem:0x60800042ebc0; uid=A28FAE879AD99B1C238309308A9071EC85D300D697100266D429A72F90B457FA, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> New Issue \U00b7 shadowsocksr/ShadowsocksX-NG (com.apple.safari.history): <CSSearchableItem:0x60800043e300; uid=71B1732664B522413B592864AE7D282D6EBCDFC3E07BE9F95FF2BC21F262AE31, bundleID=com.apple.Safari, contentType=com.apple.safari.history>",
    "<SPCoreSpotlightResult> GitHub - shadowsocksr/shadowsocksr: Python port of ShadowsocksR (com.apple.safari.history): <CSSearc
default	20:48:14.568916 +0800	loginwindow	Startup | kLWDBLogTAL | kLWDBLogLevel_Internal | -[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ShadowsocksX-NG
default	20:48:14.642816 +0800	launchservicesd	CHECKIN:0x0-0x24f24f 10648 com.qiuyuzhou.ShadowsocksX-NG
default	20:48:14.643782 +0800	loginwindow	Startup | kLWDBLogTAL | kLWDBLogLevel_Internal | -[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ShadowsocksX-NG
error	20:48:14.700469 +0800	ShadowsocksX-NG	        AEGetDescData of non-desc type 'reco' not a good idea
default	20:48:14.736827 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
default	20:48:14.921505 +0800	ShadowsocksX-NG	UNIX error exception: 17
default	20:48:14.925477 +0800	ShadowsocksX-NG	UNIX error exception: 17
default	20:48:14.928935 +0800	ShadowsocksX-NG	UNIX error exception: 17
default	20:48:14.963151 +0800	ShadowsocksX-NG	<<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder accepted for 'hvc1'
default	20:48:14.963207 +0800	ShadowsocksX-NG	VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not accepted) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-2027.4.3/Sources/VideoToolbox/VTVideoEncoderSelection.c:1343
default	20:48:14.963246 +0800	ShadowsocksX-NG	VTTileCompressionSessionCreate signalled err=-12782 (err) (Could not select and open encoder instance) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-2027.4.3/Sources/VideoToolbox/VTTile/VTTileCompressionSession.c:718
default	20:48:15.083377 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	20:48:15.150372 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	20:48:15.216749 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
default	20:48:15.218870 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	20:48:15.299244 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10658] (3,0)
default	20:48:15.319366 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10658] (3,0)
default	20:48:15.338448 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10658] (3,0)
default	20:48:15.359853 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [10646] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [10658] (3,0)
default	20:48:15.362687 +0800	ShadowsocksX-NG	pac proxy set to auto
default	20:48:24.691283 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by qinyuhang** [comment]
Could U answer the follow question? I upgrade to High Sierra and not count a crash problem. What are you doing exactly when the crash happens?

Expected behavior:

macOS High Sierra support

Actual behavior:

N/A

(N/A for feature requests)

Steps to reproduce:

(N/A for feature requests)

How often does this happen?

(N/A for feature requests)



> 在 2017年7月4日，20:52，Vincent-St <notifications@github.com> 写道：
> 
> Expected behavior:
> 
> macOS High Sierra support
> 
> Actual behavior:
> 
> N/A
> 
> (N/A for feature requests)
> 
> Steps to reproduce:
> 
> (N/A for feature requests)
> 
> How often does this happen?
> 
> (N/A for feature requests)
>

**Comment by Vincent-St** [comment]
Thanks for the help, sir. It works now on macOS High Sierra, after changing from "Proxy Auto Configure Mode" to "Global Mode". Wish you all the best.
