### ISSUE TITLE
配置文件实在找不到

### ISSUE THREAD

**Issue by didila** [shadowsocksr/ShadowsocksX-NG#188]
我利用find方式把硬盘中*ShadowsocksX*，*ss-local*以及*privoxy*文档名相关文件夹和文件全删除了
当重新下载运行，还是关联到旧的设定资料

因为出现一个讨厌的状况
我一定要删除这个配置文件
能不能告诉我这个配置文件要如何找出来

**Comment by qinyuhang** [comment]
checkout the FAQ https://github.com/shadowsocksr/ShadowsocksX-NG/issues/150 <https://github.com/shadowsocksr/ShadowsocksX-NG/issues/150>

**Comment by wangxufire** [comment]
${HOME}/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
