### ISSUE TITLE
Speed test failed and can not use on 10.12.6

### ISSUE THREAD

**Issue by zhaoxitao** [shadowsocksr/ShadowsocksX-NG#208]
Hi Yuhang,
I can't use the newest client connect to my server, I verified my sever side is no problem, because I can use my phone connect to it.
Please refer the attachment of the log file.
![2017-07-25 9 35 27](https://user-images.githubusercontent.com/8552883/28604885-afa46284-7200-11e7-9e08-f880d1b4fbbc.png)
![2017-07-26 12 55 57](https://user-images.githubusercontent.com/8552883/28604892-b69063c2-7200-11e7-87cd-2c6b73ec4b40.png)
![2017-07-26 10 50 16](https://user-images.githubusercontent.com/8552883/28604894-ba6c56ea-7200-11e7-8d4d-be503adee3cc.png)

**Comment by macron77** [comment]
Speed test can't work as expected because Sierra has removed command "sysstat", which this function depends on.

See also: https://github.com/shadowsocksr/ShadowsocksX-NG/issues/150#issuecomment-301368851

**Comment by zhaoxitao** [comment]
@macron77 Got you, thanks for your reply.
