### ISSUE TITLE
关闭ss，浏览器在休眠恢复后上不了网

### ISSUE THREAD

**Issue by sjnhnp** [shadowsocksr/ShadowsocksX-NG#32]
有人在吗 我在用10.12macos，但是发现关闭了shadowsocksX-ng，休眠后恢复mac，过一会safari和chrome都会上不了网，只能重开ss全局才行。

或者重启才能解决问题。

版本 1.3.3-R7 (1)

**Comment by sjnhnp** [comment]
其他程序都能正常连接，只有浏览器不行，开着pac自动都不行。

**Comment by qinyuhang** [comment]
可否检查一下，休眠后，系统偏好设置里面的 网络／代理呢？

**Comment by sjnhnp** [comment]
都是正常的，并且我在tg群里，也遇到和我同样问题的人。只有注销或重启才能解决。

**Comment by qinyuhang** [comment]
尝试一下在 高级设置 里面 打开 一下 Enable Verbose Mode。 然后从系统控制台 的 `~/Library/Logs` 下查看 `ss-local.log`

**Comment by timmyLan** [comment]
+1

**Comment by qinyuhang** [comment]
no following update close
