### ISSUE TITLE
希望能增加切换用户pac的功能

### ISSUE THREAD

**Issue by kdush** [shadowsocksr/ShadowsocksX-NG#46]
例如我在家里就用gfw规则就行了
但是在公司需要使用一些特别的规则
如果能切换就完美了
或者加个开关

**Comment by qinyuhang** [comment]
PAC中有 编辑pac用户自定义规则

rayzhang <notifications@github.com>于2016年10月11日 周二21:58写道：

**Comment by kdush** [comment]
但是 有需要两套规则的情况  可需求比较小众

**Comment by qinyuhang** [comment]
额 这个确实没有人有提过，我觉得你可以自己写一个脚本，替换掉 默认的 PAC 文件就可以了。 PAC 文件在 `~/.ShadowsocksX-NG/gfwlist.js`
