### ISSUE TITLE
OS X 10.11.5 无法使用，选PAC无法打开规则内的网站，选全局所有的都打不开

### ISSUE THREAD

**Issue by LoadingZhang** [shadowsocksr/ShadowsocksX-NG#53]
看到这里也有人有同样的问题，
https://github.com/shadowsocks/ShadowsocksX-NG/issues/60
但我的都赋予了执行权限，仍然无法使用
使用1.3.4-R8-build3，
系统日志显示：
16/10/19 下午6:03:16.736 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
循环上面的错误信息

**Comment by qinyuhang** [comment]
这个是说明我们用的launchd可能出问题了。需要检查 ～/Library/LaunchDaemon ～/Library/LaunchAgent
里面com.qiuyuzhou.ShadowsocksX-NG.local.plist

Loading Zhang <notifications@github.com>于2016年10月19日 周三18:04写道：

**Comment by wabcwell** [comment]
我也出现这个问题了

**Comment by delphiduan** [comment]
10.12.1, 我也出现这种情况

**Comment by jiemi** [comment]
10.11.5  出现一样的问题

**Comment by qinyuhang** [comment]
checkout FAQ problem with cleanMyMac
