### ISSUE TITLE
无法打开本地端口

### ISSUE THREAD

**Issue by Mac0ne16** [shadowsocksr/ShadowsocksX-NG#63]
以前使用的是X版本，安装NG后。本地socks端口没有开启，但是HTTP端口1087是开启的。请问这是什么情况？进程中也看不到SS-Local

**Comment by lion1991** [comment]
找到原因了么 兄弟  @Mac0ne16

**Comment by Mac0ne16** [comment]
Brew 添加了Pcre好像好了～但是之前换过几个旧版本 时好时坏的。
