### ISSUE TITLE
10.11.6 说真的 根本没用！

### ISSUE THREAD

**Issue by Puppy-Love** [shadowsocksr/ShadowsocksX-NG#69]
开启了代理，访问不了！！！ShadowsocksX 但是可以用，虽然那个一年多没更新

**Comment by lion1991** [comment]
貌似是有点小问题。我的也是无效。。

**Comment by lion1991** [comment]
升级到10.12吧 我已经可以了

**Comment by hpyer** [comment]
写着10.11以上呀～～要求已经算很高了～

**Comment by Wilson-G** [comment]
上面那个地址还是不行 gg

**Comment by qinyuhang** [comment]
用最新版

**Comment by Joney0210** [comment]
我目前使用1.3.9-R8 B10 也是不行使用

**Comment by qinyuhang** [comment]
@Joney0210 请按照git issue模版来提供信息。以及这个已经关闭的issue，不要再增加，自开issue。
