### ISSUE TITLE
网速很慢，推特等网址基本打不开

### ISSUE THREAD

**Issue by exxfzc** [shadowsocksr/ShadowsocksX-NG#74]
Mac 是最新sierra 系统，用的是最新更新的shadowsocks版本，但是发现打开动态网等网址速度很慢，而且推特，youtube网址基本打不开。帐号肯定是没有问题的，因为在win下我同样用shadowsocks，速度很快，是什么回事？

**Comment by RoyLaw** [comment]
确实觉得现在连接的效率没有其他平台的高，不过感觉尚可接受，能连上就不错了……^ ^

**Comment by qinyuhang** [comment]
是否有检查网络呢？目前我在环境好的时候，油管1080P都可以的。
