### ISSUE TITLE
1.3.8-R8（3）“打开时自动连接”失效

### ISSUE THREAD

**Issue by RoyLaw** [shadowsocksr/ShadowsocksX-NG#76]
拍手感谢1.3.8版解决了先前部分协议缺失的问题先👏～

顺便提交一个新的issue，我使用开机自启动和启动后自动连接的功能发现本地代理没有按预期启动，需要我手动“关闭Shadowsocks”后再手动开启一次。

**Comment by blankhang** [comment]
遇到同样的问题。。。。重启后 需要自己手动再次连接

**Comment by qinyuhang** [comment]
fixed
