### ISSUE TITLE
OS X10.11.6开启代理后无效

### ISSUE THREAD

**Issue by waitusz** [shadowsocksr/ShadowsocksX-NG#78]
启动后设置代理，但无法访问网站，用原版一切正常
<img width="815" alt="jt" src="https://cloud.githubusercontent.com/assets/22133928/20616295/3219f8d6-b31c-11e6-842f-3a259a4e6508.png">

**Comment by hpyer** [comment]
还以为就我有问题，，看来是通病啊～

**Comment by waitusz** [comment]
@hpyer 你说的版本我用了下，telegram可以正常使用，但浏览器不行，打不开网页

**Comment by VF128S** [comment]
同样的问题,更新之后无法访问网页,切换之前的版本也出现了同样的问题

**Comment by VF128S** [comment]
find a solution
for OS X 10.11.6
install this version-> https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.3.4-R8-fix

works on apps and browser

**Comment by hpyer** [comment]
@waitusz 你什么浏览器，是不是浏览器的代理关掉了？我用chrome没问题。或者开启全局模式，再试试能不能访问

**Comment by mpco** [comment]
解决方法：下载 [shadowsocks-libev](https://github.com/breakwa11/shadowsocks-libev)，然后编译，然后用编译产生的 src目录下的ss-local 替换 ~/Library/Application Support/ShadowsocksX-NG/ss-local-2.5.6.static/ss-local，重新运行 ShadowsocksX-NG，就可以了。

****
这个方法能解决问题，但是不符合强迫症的习惯，强迫症方法：

1. 完全卸载ShadowsocksX-NG（包括~/Library/Application Support中的文件）
2. 下载[目前最新的版本](https://github.com/qinyuhang/ShadowsocksX-NG/releases/download/1.3.8-R8-build3/ShadowsocksX-NG-R8.dmg)
3. 用编译产生的 src目录下的ss-local 替换 下载的ShadowsocksX-NG-R8.app/Contents/Resources/ss-local
4. 移至Applications目录、运行

****
编译  shadowsocks-libev 方法：

1. 安装依赖（用homebrew）：
    - asciidoc
    - xmlto
    - openssl
    - pcre
2. 设置环境变量：
```
    export LDFLAGS=-L/usr/local/opt/openssl/lib
    export CPPFLAGS=-I/usr/local/opt/openssl/include
    export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
    export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
```
3. `./configure && make`

好像是这样，应该没记错

**Comment by VF128S** [comment]
or just replace the ss-local with the old version ex 2.4.9 inside the .app folder

**Comment by sunguowei** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.3.4-R8-fix-privoxy
亲测，os X 10.11.5可用。
感谢@hpyer

**Comment by swift1112** [comment]
感谢 @mpco 终于用上了，昨天从10.11.6升级到10.12.2，下载了几个版本的NG-R客户端都不能用，按照上面的方法总算搞定。不过对于这方面很小白的我来说，mpco写的有点简略：）于是又爬了些文，依葫芦画瓢，现在把自己的步骤分享如下，希望能帮助到像我一样懵懂的朋友

打开终端进行如下操作
1、安装Homebrew：
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

2、下面四个，复制一个回车执行，待完成后再进行下一个
```
brew install asciidoc
brew install xmlto
brew install openssl
brew install pcre
```

3、设置环境变量，也是逐个回车确认
```
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
```

4、下载源码
`git clone https://github.com/shadowsocksr/shadowsocksr-libev`

5、编译，先复制下面第一行回车执行，然后再第二行
```
cd shadowsocksr-libev
./configure && make
```

6、至此终端部分操作完成，该替换ss-local文件了
编译后的ss-local 存放在 /Users/你的用户名/shadowsocksr-libev/src
按照前面mpco介绍的，

> 替换 ~/Library/Application Support/ShadowsocksX-NG/ss-local-2.5.6.static/ss-local

即可
补充一下，我是先替换 app当中的Contents/Resources/ss-local，并未起效。而新升级的10.12.2系统按上面的路径是2.5.6.1.static（ /Users/用户名/Library/Application Support/ShadowsocksX-NG/ss-local-2.5.6.1.static ）是个空文件夹，将编译后的ss-local复制到该文件夹，搞定完工！

以上，总之不知为何我的.static文件夹中没有ss-local，放入编译后的问题就解决了。

**Comment by hhstore** [comment]
@hpyer  感谢分享可用版本. 

我的`OSX 10.11.6` 用你分享的版本, 可以正常使用了, 感觉比之前访问快很多哇.
另外问一下, 当前有更新版本吗?

**Comment by chacha1024** [comment]
使用
brew install shadowsocks-libev
安装之后找到ss-local替换即可 不需要自己编译

**Comment by Joselynltt** [comment]
@swift1112 前几天突然不能用代理，后来还把mac升到了10.12.3，折腾了几天，现在用了你整理的方法终于可以了。心疼mac翻个墙好累😫

**Comment by qinyuhang** [comment]
@chacha1024 brew 安装的是ss-libev，不支持ssr功能，请周知。

**Comment by qinyuhang** [comment]
checkout the latest release
