### ISSUE TITLE
速度没手机上快

### ISSUE THREAD

**Issue by juyfchn** [shadowsocksr/ShadowsocksX-NG#82]
同一个ssr账号为什么在YouTube安卓客户端上看视频比在Mac上用网页看快几倍？

**Comment by lzfxxx** [comment]
@JulySnow Mac 版不支持混淆和协议吗，那 SSR 对比原生 SS 还有什么意义？

**Comment by BROBIRD** [comment]
@JulySnow 不支持协议和混淆？你不是来搞笑的吧？

**Comment by JulySnow** [comment]
@BROBIRD 你确认支持？我找了好长时间都没找到

**Comment by JulySnow** [comment]
@lzfxxx 原生SS是由程序直接进行 FanQ*iang 而 SSR 是 ShadowsocksX-NG这个程序是外壳 而 ss-local 才是去 进行 FanQ*iang 的 软件。

**Comment by JulySnow** [comment]
@BROBIRD Mac版本哪里支持了？

**Comment by qinyuhang** [comment]
@JulySnow 建议你仔细看看一看本repo的首页 看一看明确写了支持ssr
JulySnow <notifications@github.com>于2017年2月3日 周五11:14写道：

**Comment by wangxufire** [comment]
![](http://i1.piimg.com/567571/0bebd266b3a2318c.jpg)
@JulySnow 不是这个吗？

**Comment by JulySnow** [comment]
+1 @qinyuhang 怪我嗯 没看到 你能不能解释一下Xcode 8.2.1 OS X 10.12 提示的编译错误：
OS X 10.12 Xcode 8.2.1
已经安装依赖性环境，Debug提示如下
Ld /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/proxy_conf_helper normal x86_64
cd /Users/JulySnow/Downloads/ShadowsocksX-NG-hotfix-macOS10.12
export MACOSX_DEPLOYMENT_TARGET=10.10
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug -L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/BRLOptionParser -F/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug -filelist /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper.LinkFileList -mmacosx-version-min=10.10 -Xlinker -object_path_lto -Xlinker /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lBRLOptionParser -lPods-proxy_conf_helper -Xlinker -dependency_info -Xlinker /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_dependency_info.dat -o /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/proxy_conf_helper

ld: warning: directory not found for option '-L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/BRLOptionParser'
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JulySnow** [comment]
@wangxufire  我自己打自己的脸行不行  现在没有Mac环境 没看到
  people mountain people sea 啊！

**Comment by qinyuhang** [comment]
@JulySnow 不是给你回复了吗？在你自己的issue里面 https://github.com/shadowsocksr/ShadowsocksX-NG/issues/93 
参考issue https://github.com/shadowsocksr/ShadowsocksX-NG/issues/17
