### ISSUE TITLE
在家可以,宿舍不可以,是网络的问题?

### ISSUE THREAD

**Issue by exxfzc** [shadowsocksr/ShadowsocksX-NG#83]
同一个帐号,同一台电脑,在家速度飞快,在宿舍根本用不了.....我也是醉了
同样的中国移动宽带,也不知道是咋回事

**Comment by qinyuhang** [comment]
一般这种情况是网络问题。在环境下访问一下 ip138 看看IP，有些网段基本都被墙的很厉害，比如“鹏博士”，“广电网”
