### ISSUE TITLE
请问git clone,pull 可以走pac 或者 白名单 规则吗？

### ISSUE THREAD

**Issue by tanpengsccd** [shadowsocksr/ShadowsocksX-NG#87]

**Comment by lidashuang** [comment]
这个和items2 有关吧

**Comment by tanpengsccd** [comment]
@lidashuang 应该和网络协议有关吧。iterm 2 只是个终端啊

**Comment by qinyuhang** [comment]
试试 export http_proxy=127.0.0.1:1087

**Comment by hye** [comment]
`git config --global https.proxy 127.0.0.1:1087` (但好像并没有加速-。-，而且好容易出The remote end hung up unexpectedly 难道ss也被墙重点关注了？）

**Comment by tanpengsccd** [comment]
ss早被关注了。原作者都被请喝茶了。我的git 代理也感觉很慢了发自网易邮箱大师
            在2017年01月08日 13:19，hye 写道:git config --global https.proxy 127.0.0.1:1087 (但好像并没有加速-。-，而且好容易出The remote end hung up unexpectedly 难道ss也被墙重点关注了？）

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocksr/ShadowsocksX-NG","title":"shadowsocksr/ShadowsocksX-NG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocksr/ShadowsocksX-NG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hye in #87: `git config --global https.proxy 127.0.0.1:1087` (但好像并没有加速-。-，而且好容易出The remote end hung up unexpectedly 难道ss也被墙重点关注了？）"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocksr/ShadowsocksX-NG/issues/87#issuecomment-271130814"}}}

**Comment by tanpengsccd** [comment]
你这个貌似没对。要走socks5代理。http://note.youdao.com/noteshare?id=2be806b5a8cc1dd23391196b4d505e9f发自网易邮箱大师
            在2017年01月08日 13:19，hye 写道:git config --global https.proxy 127.0.0.1:1087 (但好像并没有加速-。-，而且好容易出The remote end hung up unexpectedly 难道ss也被墙重点关注了？）

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocksr/ShadowsocksX-NG","title":"shadowsocksr/ShadowsocksX-NG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocksr/ShadowsocksX-NG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hye in #87: `git config --global https.proxy 127.0.0.1:1087` (但好像并没有加速-。-，而且好容易出The remote end hung up unexpectedly 难道ss也被墙重点关注了？）"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocksr/ShadowsocksX-NG/issues/87#issuecomment-271130814"}}}

**Comment by tanpengsccd** [comment]
找到方法了，proxychains-ng 和ss配合。或者 git 设置代理
