### ISSUE TITLE
ssR無法使用

### ISSUE THREAD

**Issue by ookangzheng** [shadowsocksr/ShadowsocksX-NG#92]
Mac os 10.12.2
伺服器vultr
手機上的ssr配置成功，但電腦Mac使用ssR的無法..同樣的用ss-libev 這個正常，沒問題
想說要怎麼解決啊

**Comment by qinyuhang** [comment]
检查一下你的配置有没有填写错。网络环境如何。最后还不行的话，开始啰嗦模式，然后运行一段时间，把详细log上传到此issue，谢谢。

**Comment by BIOTONIC** [comment]
@qinyuhang 小白一个 SSR也是无法使用 但是找不到原因 请教一下怎么记录log啊

**Comment by qinyuhang** [comment]
About log check@ https://github.com/shadowsocksr/ShadowsocksX-NG/issues/62

**Comment by ookangzheng** [comment]
我後來搞定了~~

**Comment by BIOTONIC** [comment]
对应目录下找不到ss-local.log文件是不是说明ss-local没有运行起来？ @qinyuhang

**Comment by qinyuhang** [comment]
@BIOTONIC possible, check the `Console.app` for `ShadowsocksX-NG` log.

**Comment by BIOTONIC** [comment]
我这里Global模式下 Safari、AppStore或者从AppStore下载的应用都连不了网
而从第三方下载的应用还是能联网
是不是说明后者没用走代理 所以还能联网？@qinyuhang

**Comment by BIOTONIC** [comment]
也没有找到 @qinyuhang

**Comment by qinyuhang** [comment]
If the `ShadowsocksX-NG-R` app did launch successfully in ur Mac, there is definitely log in `Console.app`,  do u confirm there is no log of the app? Since u cannot provide any of those information, I wish to help u but I can’t.

How to make a valid GitHub issue https://github.com/shadowsocksr/ShadowsocksX-NG/issues/31 <https://github.com/shadowsocksr/ShadowsocksX-NG/issues/31>

**Comment by BIOTONIC** [comment]
ss-local.log确实没有 只能找到ShadowsocksX-NG的log 
Global模式下网页都无法访问 但是ping服务器可以 
更新GFW List时有报错 如下：
TIC TCP Conn Event [3:0x60800019b110]: 3 Err(61)
TIC TCP Conn Failed [3:0x60800019b110]: 1:61 Err(61)
TIC TCP Conn Cancel [3:0x60800019b110]
TIC TCP Conn Destroyed [3:0x60800019b110]
HTTP load failed (error code: -1004 [1:61])
NSURLSessionTask finished with error - code: -1004
当前版本是1.3.9-R8(6)
系统是10.12.3 在10.12.2的时候就有这个问题了

**Comment by qinyuhang** [comment]
Try PAC mode or White list mode?

**Comment by BIOTONIC** [comment]
我修改过hosts文件 除了Youtube视频不能播放 其他大部分网站都能正常打开 
PAC模式或者白名单作用一样 Youtube还是不能播放 其他网站也都正常打开 也就是没起到代理的作用
@qinyuhang

**Comment by qinyuhang** [comment]
Maybe the server is not working? Did u try the server on ur phone? Maybe consult ur SS seller?

**Comment by BIOTONIC** [comment]
每次运行ShadowsocksX-NG的时候 Console会提示Start ss-local succeeded. 
但是这个进程找不到 也没有找到ss-local.log
@qinyuhang

**Comment by BIOTONIC** [comment]
我试过一个SS账号 一个SSR账号 
手机上都能运行
Mac上不支持rss的ShadowsocksX.app可以运行SS账号
而这个ShadowsocksX-NG.app两个账号都运行不了
@qinyuhang

**Comment by qinyuhang** [comment]
Ur information if not enough for debug. See below:
How to make a valid GitHub issue https://github.com/shadowsocksr/ShadowsocksX-NG/issues/31 <https://github.com/shadowsocksr/ShadowsocksX-NG/issues/31>

**Comment by BIOTONIC** [comment]
ss-local.log确实没有找到 没办法啦 能提供的信息也就上述那么多了
@qinyuhang
