### ISSUE TITLE
请问怎么在哪里编辑pac.txt文件，我想加入一些域名进白名单？

### ISSUE THREAD

**Issue by szy0syz** [shadowsocksr/ShadowsocksX-NG#94]
macos 新手。😄

**Comment by wangxufire** [comment]
菜单 编辑PAC用户自定规则
JerryShi <notifications@github.com>于2017年1月25日 周三15:50写道：

**Comment by szy0syz** [comment]
@wangxufire 谢谢，可以用用了，但似乎要代理的模式切换成白名单模式才行。
