### ISSUE TITLE
服务器测速崩溃

### ISSUE THREAD

**Issue by blankhang** [shadowsocksr/ShadowsocksX-NG#97]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.3 (16E144f)
- Shadowsocksx-NG-R8 1.3.9-R8-build6-GCDPing

测试服务器速度100%crash

[ShadowsocksX-NG_2017-02-03-113119_blankdeMacBook-Pro.crash.zip](https://github.com/shadowsocksr/ShadowsocksX-NG/files/749526/ShadowsocksX-NG_2017-02-03-113119_blankdeMacBook-Pro.crash.zip)
[ss-local_2017-02-03-110720_blankdeMacBook-Pro.crash.zip](https://github.com/shadowsocksr/ShadowsocksX-NG/files/749528/ss-local_2017-02-03-110720_blankdeMacBook-Pro.crash.zip)

**Comment by qinyuhang** [comment]
It looks like your ss-local is not compiled with libpcre. maybe try this.
[ss-local.zip](https://github.com/shadowsocksr/ShadowsocksX-NG/files/749538/ss-local.zip)

**Comment by blankhang** [comment]
不会弄= = 
我退回到 倒数第2的版本 正常了
