### ISSUE TITLE
remote_recv_cb_recv: Connection reset by peer

### ISSUE THREAD

**Issue by wuzhefang** [shadowsocksr/ShadowsocksX-NG#98]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.3 (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

**问题描述**
刚刚升级到10.12.3，之前一直使用的是EICapton，log信息如下。
不知道为什么就是无法使用了，log信息中只有ERROR: remote_recv_cb_recv: Connection reset by peer，没有别的log。
请问这可能是什么原因，应该如何排查

**ss-local.log**

2017-02-06 15:29:07 INFO: protocol origin
 2017-02-06 15:29:07 INFO: protocol_param
 2017-02-06 15:29:07 INFO: method chacha20
 2017-02-06 15:29:07 INFO: obfs plain
 2017-02-06 15:29:07 INFO: obfs_param
 2017-02-06 15:29:07 INFO: initializing ciphers... chacha20
 2017-02-06 15:29:08 INFO: tcp port reuse enabled
 2017-02-06 15:29:08 INFO: listening at 127.0.0.1:1086
 2017-02-06 15:39:49 ERROR: remote_recv_cb_recv: Connection reset by peer
 2017-02-06 15:39:50 ERROR: remote_recv_cb_recv: Connection reset by peer
 2017-02-06 15:39:53 ERROR: remote_recv_cb_recv: Connection reset by peer
 2017-02-06 15:39:55 ERROR: remote_recv_cb_recv: Connection reset by peer
 2017-02-06 15:39:56 ERROR: remote_recv_cb_recv: Connection reset by peer
 2017-02-06 15:39:56 ERROR: remote_recv_cb_recv: Connection reset by peer
**Application log**
默认	16:01:48.533860 +0800	ShadowsocksX-NG	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
默认	16:01:48.676737 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
默认	16:01:48.741924 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
默认	16:01:48.742186 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	16:01:48.753809 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	16:01:48.755766 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34160] (3,0)
默认	16:01:48.757943 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34160] (3,0)
默认	16:01:48.761647 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34160] (3,0)
默认	16:01:48.762560 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34160] (3,0)
默认	16:01:48.764618 +0800	ShadowsocksX-NG	pac proxy set to off
默认	16:01:48.832030 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
默认	16:01:48.900935 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	16:01:48.966232 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	16:01:48.966461 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	16:01:48.978005 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	16:01:48.979996 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34169] (3,0)
默认	16:01:48.982127 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34169] (3,0)
默认	16:01:48.985907 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34169] (3,0)
默认	16:01:48.986924 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34169] (3,0)
默认	16:01:48.988730 +0800	ShadowsocksX-NG	pac proxy set to off
默认	16:01:48.989628 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	16:01:49.000031 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	16:01:49.002169 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34170] (3,0)
默认	16:01:49.004452 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34170] (3,0)
默认	16:01:49.008556 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34170] (3,0)
默认	16:01:49.009386 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34057] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34170] (3,0)
默认	16:01:49.011455 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	16:02:32.122783 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	16:02:32.187987 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	16:02:32.188244 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	16:02:32.199934 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	16:02:32.210996 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34264] (3,0)
默认	16:02:32.213524 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34264] (3,0)
默认	16:02:32.217423 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34264] (3,0)
默认	16:02:32.218254 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34264] (3,0)
默认	16:02:32.220380 +0800	ShadowsocksX-NG	pac proxy set to off
默认	16:02:32.220741 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	16:02:32.231731 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	16:02:32.233792 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34266] (3,0)
默认	16:02:32.236005 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34266] (3,0)
默认	16:02:32.239816 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34266] (3,0)
默认	16:02:32.240708 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [34265] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [34266] (3,0)
默认	16:02:32.242702 +0800	ShadowsocksX-NG	pac proxy set to off

**Comment by wuzhefang** [comment]
唉，找到原因了，加密算法大小写有区别，chacha20 不等于 CHACHA20，二维码扫描进去的默认是大写的。

**Comment by qinyuhang** [comment]
从日志看，app本身没有发生fatal， ss-local 也没有fatal，可以考虑从一下方面着手：1 ss账号是不是被封号了？ 2 服务器问题？ 3 信息填写错误？

**Comment by breakwa11** [comment]
@wuzhefang 这应该找你的二维码提供者

**Comment by wuzhefang** [comment]
这个二维码是我从手机的app里生成的，可能有问题。

这个加密算法是大小写敏感的？

-- 
Zhefang Wu
Beijing,China

开 2017年2月6日 在 下午4:21:48, 破娃酱 (notifications@github.com) 写到:

@wuzhefang 这应该找你的二维码提供者

**Comment by breakwa11** [comment]
@wuzhefang 什么APP

**Comment by wuzhefang** [comment]
Shadowrocket

-- 
Zhefang Wu
Beijing,China

开 2017年2月6日 在 下午4:31:09, 破娃酱 (notifications@github.com) 写到:

@wuzhefang 什么APP

**Comment by breakwa11** [comment]
作者说并不是

**Comment by wuzhefang** [comment]
是哟。我记错了，二维码是从tizipuss.com/ 生成的，我刚才又测试了一下。

-- 
Zhefang Wu
Beijing,China

开 2017年2月6日 在 下午4:47:15, 破娃酱 (notifications@github.com) 写到:

作者说并不是

**Comment by breakwa11** [comment]
@wuzhefang 那你找生成的站的站长问

**Comment by wuzhefang** [comment]
嗯，告诉他一下😄

-- 
Zhefang Wu
Beijing,China

开 2017年2月6日 在 下午5:06:22, 破娃酱 (notifications@github.com) 写到:

@wuzhefang 那你找生成的站的站长问
